//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo5
    {
        public int IDGrupo5 { get; set; }
        public string PruebaNombre { get; set; }
        public string Telefono { get; set; }
        public string Correito { get; set; }
    }
}
