//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int User_ID { get; set; }
        public string Password { get; set; }
        public string National_ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    }
}
